version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      gomod:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      docker:
        patterns:
          - "*"

  - package-ecosystem: terraform
    directory: /terraform
    schedule:
      interval: weekly
      day: monday
    groups:
      terraform:
        patterns:
          - "*"
