name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:
  go-checks:
    name: Run Go Checks
    uses: densestvoid/workflows/.github/workflows/go-checks.yml@main
